name: Scheduled Python Scripts

on:
  schedule:
    - cron: "0 0 1 * *"  # Le 1er jour de chaque mois à minuit
  workflow_dispatch:  # Permet d'exécuter le workflow manuellement
  push:
    branches:
      - RecupData  # Exécuter uniquement sur la branche 'RecupData'

jobs:
  run-monthly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: RecupData

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scripts
        run: |
          cd docs/Code/
          python ImportXmlOnlyFileTemporary.py
          python ImportXmlOnlyFileAdmin.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Mise à jour automatique des fichiers générés (Mensuel)" || exit 0
          git push origin RecupData
        continue-on-error: true
